### ISSUE TITLE
Support for water heaters

### ISSUE THREAD

**Issue by ablyler** [mulcmu/esphome-ge-laundry-uart#10]
I am the maintainer for the [Home Assistant Bradford White Connect](https://github.com/ablyler/home-assistant-bradford-white-connect). The connect device appears to be a ESP32 board that is talking the GEA2 protocol to the water heater via a RJ45 connection.

I am interested in helping add support for water heaters with your project or creating a sibling project. Any help you could provide me on how to get started would be great! I am new to all this low level stuff. How can I use your PCB board design to build a board that I could start iterating on?

I did find this [documentation](https://github.com/doitaljosh/geabus-documentation/blob/master/hewh-interface.docx) that appears to be a good start for how to send commands to the water heater.

**Comment by mguaylam** [comment]
You can buy the board from FirstBuild or look [here](https://github.com/geappliances/home-assistant-adapter/blob/main/doc/schematic-v1.0.pdf).

**Comment by ablyler** [comment]
> You can buy the board from FirstBuild or look [here](https://github.com/geappliances/home-assistant-adapter/blob/main/doc/schematic-v1.0.pdf).

Ah, it looks like the board isn't available to order yet, I did sign up for the beta.

**Comment by mulcmu** [comment]
I had used a lot of the information from the doitaljosh repositories when I was developing this project.

The other FirstBuild/GeMakers repository has official details on the water heater [erds](https://github.com/geappliances/public-appliance-api-documentation/blob/36e7e1dbee7e1ad33003941ec5ac44ccb20b119b/appliance_api.json#L188-L262).  They also have a home assistant repository so it looks like some nice non-cloud stuff is being developed.  A big change from where they were about a year [ago](https://hackaday.com/2024/01/19/haier-threatens-legal-action-against-home-assistant-plugin-developer/).

**Comment by mguaylam** [comment]
I do have the board working if you have any questions.

**Comment by ablyler** [comment]
> I do have the board working if you have any questions.

Did you get the board from FirstBuild or build it yourself? It looks like the board supports gea2, but I only see gea3 referenced in their code.

**Comment by mguaylam** [comment]
Yes I got it from FirstBuild. I believe the board support GEA2 & 3 because I can see silk-mark identifying both protocols. But they only implemented GEA3 for now. You could ask on this [repo](https://github.com/geappliances/home-assistant-adapter) perhaps? They wrote the [tiny gea3 api](https://github.com/geappliances/tiny-gea3-api) so I guess someone would need to do the same for GEA2.

**Comment by ablyler** [comment]
Thanks! I actually posted an [issue](https://github.com/geappliances/home-assistant-adapter/issues/5) a bit ago on that repo. 😀 We can close this issue, as I think I'll pursue the FirstBuild route.
